package proyectoDAO;
// Generated 08-may-2018 19:15:02 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Carta generated by hbm2java
 */
public class Carta implements java.io.Serializable {

	private int pkIdCarta;
	private String nombrePlato;
	private String ingredientes;
	private Set restaurantexcartas = new HashSet(0);

	public Carta() {
	}

	public Carta(int pkIdCarta, String nombrePlato) {
		this.pkIdCarta = pkIdCarta;
		this.nombrePlato = nombrePlato;
	}

	public Carta(int pkIdCarta, String nombrePlato, String ingredientes, Set restaurantexcartas) {
		this.pkIdCarta = pkIdCarta;
		this.nombrePlato = nombrePlato;
		this.ingredientes = ingredientes;
		this.restaurantexcartas = restaurantexcartas;
	}

	public int getPkIdCarta() {
		return this.pkIdCarta;
	}

	public void setPkIdCarta(int pkIdCarta) {
		this.pkIdCarta = pkIdCarta;
	}

	public String getNombrePlato() {
		return this.nombrePlato;
	}

	public void setNombrePlato(String nombrePlato) {
		this.nombrePlato = nombrePlato;
	}

	public String getIngredientes() {
		return this.ingredientes;
	}

	public void setIngredientes(String ingredientes) {
		this.ingredientes = ingredientes;
	}

	public Set getRestaurantexcartas() {
		return this.restaurantexcartas;
	}

	public void setRestaurantexcartas(Set restaurantexcartas) {
		this.restaurantexcartas = restaurantexcartas;
	}

}
