package proyectoDAO;
// Generated 08-may-2018 19:15:02 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Restaurante generated by hbm2java
 */
public class Restaurante implements java.io.Serializable {

	private int pkIdRestaurante;
	private String nombreRestaurante;
	private String direccion;
	private Integer telefono;
	private Set restaurantexcartas = new HashSet(0);

	public Restaurante() {
	}

	public Restaurante(int pkIdRestaurante) {
		this.pkIdRestaurante = pkIdRestaurante;
	}

	public Restaurante(int pkIdRestaurante, String nombreRestaurante, String direccion, Integer telefono,
			Set restaurantexcartas) {
		this.pkIdRestaurante = pkIdRestaurante;
		this.nombreRestaurante = nombreRestaurante;
		this.direccion = direccion;
		this.telefono = telefono;
		this.restaurantexcartas = restaurantexcartas;
	}

	public int getPkIdRestaurante() {
		return this.pkIdRestaurante;
	}

	public void setPkIdRestaurante(int pkIdRestaurante) {
		this.pkIdRestaurante = pkIdRestaurante;
	}

	public String getNombreRestaurante() {
		return this.nombreRestaurante;
	}

	public void setNombreRestaurante(String nombreRestaurante) {
		this.nombreRestaurante = nombreRestaurante;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Integer getTelefono() {
		return this.telefono;
	}

	public void setTelefono(Integer telefono) {
		this.telefono = telefono;
	}

	public Set getRestaurantexcartas() {
		return this.restaurantexcartas;
	}

	public void setRestaurantexcartas(Set restaurantexcartas) {
		this.restaurantexcartas = restaurantexcartas;
	}

}
