package proyectoDAO;
// Generated 08-may-2018 19:15:02 by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Restaurantexcarta generated by hbm2java
 */
public class Restaurantexcarta implements java.io.Serializable {

	private int pkIdMenu;
	private Carta carta;
	private Restaurante restaurante;
	private Set pedidos = new HashSet(0);

	public Restaurantexcarta() {
	}

	public Restaurantexcarta(int pkIdMenu) {
		this.pkIdMenu = pkIdMenu;
	}

	public Restaurantexcarta(int pkIdMenu, Carta carta, Restaurante restaurante, Set pedidos) {
		this.pkIdMenu = pkIdMenu;
		this.carta = carta;
		this.restaurante = restaurante;
		this.pedidos = pedidos;
	}

	public int getPkIdMenu() {
		return this.pkIdMenu;
	}

	public void setPkIdMenu(int pkIdMenu) {
		this.pkIdMenu = pkIdMenu;
	}

	public Carta getCarta() {
		return this.carta;
	}

	public void setCarta(Carta carta) {
		this.carta = carta;
	}

	public Restaurante getRestaurante() {
		return this.restaurante;
	}

	public void setRestaurante(Restaurante restaurante) {
		this.restaurante = restaurante;
	}

	public Set getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set pedidos) {
		this.pedidos = pedidos;
	}

}
